version: "3"

includes:
  backend:
    taskfile: ./backend/Taskfile.yaml
    dir: ./backend
  frontend:
    taskfile: ./frontend/Taskfile.yaml
    dir: ./frontend

tasks:
  run:
    desc: Run application
    cmds:
      - npm start
  check:
    desc: Run CI checks
    cmds:
      - task: lint
  lint:
    desc: Run lint
    cmds:
      - task: backend:lint
      - task: frontend:lint
